server:
  port: 8000

#  怎么给这个项目自动添加一个名字呢？对每个页面都有一定的处理了。
  servlet.context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
#    Java Persistence API
#    缓存数据
  redis:
    host: 192.168.159.100
    port: 6379
    database: 0
swagger:
  applicationName: securityDemo
  applicationVersion: 1.0
  applicationDescription: demo登录

mybatisplus:
  enabled: true
  generic:
    enabled: true
  dialectType: mysql
#  扫描的路径

  mybatis.mapper-locations: classpath*:mapper/*.xml
  logging:
    level: debug
  global-config:
    db-config:
      table-underline: true

